services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $autoPrune: '%shapecode_cron.results.auto_prune%'
            $pruneInterval: '%shapecode_cron.results.interval%'

    # manager
    Shapecode\Bundle\CronBundle\Manager\:
        resource: '../../Manager/*'

    # commands
    Shapecode\Bundle\CronBundle\Command\:
        resource: '../../Command/*'

    # controller
    Shapecode\Bundle\CronBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    # cronjobs
    Shapecode\Bundle\CronBundle\CronJob\GenericCleanUpDailyCommand:
        tags:
            - { name: console.command }
            - { name: shapecode_cron.cron_job, expression: '@daily' }

    Shapecode\Bundle\CronBundle\CronJob\GenericCleanUpHourlyCommand:
        tags:
            - { name: console.command }
            - { name: shapecode_cron.cron_job, expression: '@hourly' }

    # event listener
    Shapecode\Bundle\CronBundle\EventListener\EntitySubscriber:
        tags: ['doctrine.event_subscriber']

    Shapecode\Bundle\CronBundle\EventListener\:
        resource: '../../EventListener/*'

    # service
    Shapecode\Bundle\CronBundle\Service\:
        resource: '../../Service/*'
